name: Workflow BETELGEUSE

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install tox and any other packages
        run: pip install tox
        working-directory: ./backend

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./

      - name: Run tox
        run: tox -e py
        working-directory: ./backend

      - name: XML Fix Format
        run: |
          xml_file_path="coverage.xml"
          new_filename_prefix="backend"
          sed -i "s|filename=\"\(.*\)\"|filename=\"$new_filename_prefix\/\1\"|g" "$xml_file_path"
        working-directory: ./backend

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL  }}
